site_name: Tanaguru Sonar plugin
pages:
- ['index.md', 'Home']
- ['install.md', 'Installation']
- ['configuration.md', 'Configuration']
- ['run-with-sonar-runner.md', 'Run with SonarQube Runner']
- ['run-with-maven.md', 'Run with Maven']
- ['run-with-jenkins.md', 'Run with SonarQube Jenkins plugin']
- ['run-with-eclipse.md', 'Run with SonarQube Eclipse plugin']
- ['developer-doc.md', 'Developer doc']

theme: readthedocs
repo_url: https://github.com/Tanaguru/sonar-tanaguru
